[package]
name = "btwallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "btwallet"
crate-type = ["cdylib"]

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
base58 = "0.2.0"
bip39 = "2.0.0"
blake2 = "0.10.6"
generic-array = "1.1.0"
hex = "0.4.3"
hmac = "0.12.1"
pbkdf2 = "0.12.2"
primitive-types = "0.12.2"
pyo3 = { version = "0.22.0", features = ["extension-module"] }

ring = "0.17"
rand = "0.8.5"
regex = "1.10.6"
schnorrkel = "0.11.4"
secp256k1 = "0.29.0"
serde = "1.0.208"
sha2 = "0.10.8"
sp-core = "34.0.0"
sp-runtime = "39.0.0"
uint = "0.9.5"
serde_json = "1.0"
thiserror = "1.0"
shellexpand = "2.1"
secrets = "1.2"